# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: 'main'
    weight: 10
  - name: About
    parent: "main"
    url: '#about'
    weight: 11
  - name: Contact
    parent: "main"
    url: '#contact'
    weight: 12
  - name: News
    url: 'news/'
    weight: 20
  - name: Projects
    url: 'projects/'
    weight: 30
  - name: Publications
    url: 'publication/'
    weight: 40
  - name: Outreach & Media
    url: 'media/'
    weight: 50
  - name: Other
    identifier: 'other'
    weight: 60
  - name: Conferences
    parent: "other"
    url: 'conference'
    weight: 61
  - name: Blog posts
    parent: "other"
    url: 'post/'
    weight: 62

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
