---
title: Projects
summary: List of projects.
date: ""

reading_time: false  # Show estimated reading time?
share: false  # Show social sharing links?
profile: false  # Show author profile?
comments: false  # Show comments?

# Optional header image (relative to `static/img/` folder).
#header: 
#caption: ""
#image: ""
---

## **PhD project**

My PhD focuses on understanding the process of horizontal transfer of antimicrobial resistance genes.
We know that bacteria can exchange genes encoding antimicrobial resistance between them, however the exact dynamics of this are still unclear. At which rate does this occur? What influences the speed of the process? What is the impact of horizontal transfer on the overall public health consequences of antimicrobial resistance? These are some of the questions I'm trying to answer!

My supervisors are [Dr Gwen Knight](https://gwenknight.github.io/) (LSHTM) and [Prof Jodi Lindsay](https://www.sgul.ac.uk/profiles/jodi-lindsay) (SGUL), and I am funded by an [MRC LID studentship](http://mrc-lid.lshtm.ac.uk/).

My relevant publications for this can be found [here](/categories/phd-project/).

<br>

***

<br>

## **COVID-19**

I am currently involved in the COVID-19 response work by the Centre of Mathematical Modelling of Infectious Diseases at LSHTM. Notably, I contribute to the daily maintenance of our data pipeline, and have conducted various analyses on COVID-19 transmission in different settings.

A complete list of the most recent coronavirus work by CMMID can be found [here](https://cmmid.github.io/topics/covid19/)

My relevant publications for this can be found [here](/categories/covid-19/).

<br>

***

<br>

## **Wellcome Data Reuse Prize**

Alongside several colleagues from LSHTM, I contributed to the winning entry for the [Data Re-use Prize](https://wellcome.ac.uk/news/new-data-re-use-prizes-help-unlock-value-research), a competition launched by the Wellcome Trust in 2018.
We combined multiple open-access data sources to inform empiric prescribing of antibiotics around the world.

My relevant publications for this can be found [here](/publication/empiricprescribing/).

<br>

***

<br>

## **Previous projects**

As part of my previous studies, I was involved in other research projects:

* #### Comparing the Analysis and Results of a Modified Social Accounting Matrix Framework with Conventional Methods of Reporting Indirect Non-Medical Costs
In 2019 I completed a 3 months placement in the Value Evidence team at GlaxoSmithKline (Wavres, Belgium). During this period, I worked on cost of disease evaluation, cost-effectiveness analysis and fiscal modelling.

    Part of my work has been published, see [here](/publication/samindirectcosts/) for details.


* #### The effect of structure and resolution on the dynamics of spatial epidemic models
In my MSc project, I examined the link between the spatial scale at which we simulate epidemics and the results of such simulations. I focused on influenza in England, and developed a complete dynamic spatial model in R.

    For this, I was supervised by [Dr David Haw](https://www.imperial.ac.uk/people/d.haw) and [Prof Steven Riley](https://www.imperial.ac.uk/people/s.riley).

* #### Assessing the community impact of insecticide-treated nets for malaria control
This was my very first project on mathematical modelling, in the final year of my BSc. I modified an existing transmission dynamics model of malaria to visualise the indirect protection provided by insecticide-treated nets against mosquito bites.

    I was supervised by [Dr Thomas Churcher](https://www.imperial.ac.uk/people/thomas.churcher), to whom I am eternally grateful for introducing me to the field of mathematical modelling!





